<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <Compile Remove="Application\**" />
    <EmbeddedResource Remove="Application\**" />
    <None Remove="Application\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\shared\DentalClinic.SharedKernel\DentalClinic.SharedKernel.csproj" />
    <ProjectReference Include="..\BookingService.Domain\BookingService.Domain.csproj" />
    <PackageReference Include="Dapr.Client" Version="1.16.1" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
